name: "Prod Deploy"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::823993466004:role/github-actions-terraform-tutorial-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "githubactions-sa-east-1-terraform-pipeline-tutorial-statefile"
      aws-lock-dynamodb-table: "githubactions-sa-east-1-terraform-tutorial-lock"
